site_name: CasGists Documentation
site_description: Self-hosted GitHub Gist alternative for non-technical users and SMBs
site_author: CasApps
site_url: https://casgists.readthedocs.io

repo_name: casapps/casgists
repo_url: https://github.com/casapps/casgists
edit_uri: edit/main/docs/

theme:
  name: material
  palette:
    # Dracula theme colors
    - scheme: dracula
      primary: deep purple
      accent: pink
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
  font:
    text: Roboto
    code: JetBrains Mono
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.code.annotate
  icon:
    repo: fontawesome/brands/github

extra_css:
  - stylesheets/dracula.css

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - tables
  - toc:
      permalink: true
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: true

nav:
  - Home: index.md
  - Getting Started:
    - Quick Start: QUICK_START.md
    - Getting Started Guide: GETTING_STARTED.md
    - Installation: installation.md
  - User Guide:
    - User Guide: user-guide.md
    - Configuration: configuration.md
  - Admin Guide:
    - Admin Guide: admin-guide.md
    - Production Deployment: production-deployment.md
  - Deployment:
    - Overview: deployment.md
    - Deployment Guide: deployment/DEPLOYMENT_GUIDE.md
    - Deployment Options: deployment/DEPLOYMENT.md
    - Installation Guide: deployment/INSTALL.md
    - Migration Guide: deployment/MIGRATION_GUIDE.md
  - API Reference:
    - API Overview: api.md
    - API Reference: api-reference.md
    - API Examples: api/API_EXAMPLES.md
    - Feature Reference: api/FEATURE_REFERENCE.md
  - Architecture & Compliance:
    - Architecture Overview: ARCHITECTURE.md
    - Compliance: COMPLIANCE.md
    - Performance: PERFORMANCE.md
  - Project Info:
    - Changelog: CHANGELOG.md
    - Release Notes: RELEASE_NOTES.md
    - Release Process: RELEASE.md
    - Specification: ../SPEC.md
    - Compliance Status: SPEC_COMPLIANCE.md
    - TODO List: TODO.md

extra:
  version:
    provider: mike
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/casapps/casgists
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/r/casapps/casgists
